openapi: 3.0.0
info:
  title: Otopark-API
  version: 1.0.0
servers:
  - url: https://otopark-api.herokuapp.com/api/v1
  - url: http://{{url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/register:
    post:
      tags:
        - default
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: susan
                email: susan@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - default
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: susan@gmail.com
                password: secret
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot:
    get:
      tags:
        - default
      summary: Get Slots
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Slot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                parkingSlot: P-5
                isFull: true
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot/631a09cc50e83d19d4fefcb6:
    patch:
      tags:
        - default
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                parkingSlot: P-1
                isFull: false
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /slot/637013a9c647f03ce4b39713:
    delete:
      tags:
        - default
      summary: Delete User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}